version: '3.9'

services:
  db:
    image: ${DOCKER_USERNAME}/my_c2wk_db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  app:
    image: ${DOCKER_USERNAME}/my_c2wk_app:latest
    ports:
      - '${PORT}:${PORT}'
    environment:
      - DB_HOST=db
      - DB_USER=$DATABASE_USER
      - DB_PASSWORD=$DATABASE_PASSWORD
      - DB_NAME=$DATABASE_NAME
      - DB_PORT=$DATABASE_PORT
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

volumes:
  mysql_data:
